# deploy/argo/ems-app.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ems-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/UchihaIthachi/EMS
    targetRevision: HEAD
    path: deploy/k8s
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: ems-app
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
