apiVersion: v1
kind: Secret
metadata:
  name: department-db-secret
  namespace: ems-app
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: "bXlzcWw=" # echo -n 'mysql' | base64
  MYSQL_USER: "ZGVwYXJ0bWVudF91c2Vy" # echo -n 'department_user' | base64
  MYSQL_PASSWORD: "ZGVwYXJ0bWVudF9wYXNzd29yZA==" # echo -n 'department_password' | base64
