apiVersion: v1
kind: Secret
metadata:
  name: employee-db-secret
  namespace: ems-app
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: "bXlzcWw=" # echo -n 'mysql' | base64
  MYSQL_USER: "ZW1wbG95ZWVfdXNlcg==" # echo -n 'employee_user' | base64
  MYSQL_PASSWORD: "ZW1wbG95ZWVfcGFzc3dvcmQ=" # echo -n 'employee_password' | base64
