apiVersion: v1
kind: Service
metadata:
  name: api-gateway
  namespace: ems-app
  labels:
    app: api-gateway
spec:
  selector:
    app: api-gateway
  type: ClusterIP
  ports:
    - name: http
      port: 8080
      targetPort: 8080
