apiVersion: v1
kind: Service
metadata:
  name: config-server
  namespace: ems-app
  labels:
    app: config-server
spec:
  selector:
    app: config-server
  type: ClusterIP
  ports:
    - name: http
      port: 8888
      targetPort: 8888
