apiVersion: v1
kind: Service
metadata:
  name: department-service
  namespace: ems-app
  labels:
    app: department-service
spec:
  selector:
    app: department-service
  type: ClusterIP
  ports:
    - name: http
      port: 8081
      targetPort: 8081
