apiVersion: v1
kind: Service
metadata:
  name: employee-service
  namespace: ems-app
  labels:
    app: employee-service
spec:
  selector:
    app: employee-service
  type: ClusterIP
  ports:
    - name: http
      port: 8082
      targetPort: 8082
