apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: ems-app
  labels:
    app: frontend
spec:
  selector:
    app: frontend
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: 80
