apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: ems-app
  labels:
    app: grafana
spec:
  selector:
    app: grafana
  type: ClusterIP
  ports:
    - name: http
      port: 3000
      targetPort: 3000
