apiVersion: v1
kind: Service
metadata:
  name: logstash
  namespace: ems-app
  labels:
    app: logstash
spec:
  selector:
    app: logstash
  type: ClusterIP
  ports:
    - name: tcp-input
      port: 5000
      targetPort: 5000
