apiVersion: v1
kind: Service
metadata:
  name: mysql-department
  namespace: ems-app
  labels:
    app: mysql-department
spec:
  selector:
    app: mysql-department
  ports:
    - name: mysql
      port: 3306
      targetPort: 3306
