apiVersion: v1
kind: Service
metadata:
  name: mysql-employee
  namespace: ems-app
  labels:
    app: mysql-employee
spec:
  selector:
    app: mysql-employee
  ports:
    - name: mysql
      port: 3306
      targetPort: 3306
