apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: ems-app
  labels:
    app: prometheus
spec:
  selector:
    app: prometheus
  type: ClusterIP
  ports:
    - name: http
      port: 9090
      targetPort: 9090
