apiVersion: v1
kind: Service
metadata:
  name: service-registry
  namespace: ems-app
  labels:
    app: service-registry
spec:
  selector:
    app: service-registry
  type: ClusterIP
  ports:
    - name: http
      port: 8761
      targetPort: 8761
