apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: ems-app
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: ghcr.io/uchihaithachi/frontend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 5
          resources:
            requests:
              cpu: "75m"  # Was 100m
              memory: "128Mi" # Adjusted as frontend might be lower
            limits:
              cpu: "500m"
              memory: "256Mi" # Adjusted as frontend might be lower
