apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-registry
  namespace: ems-app
  labels:
    app: service-registry
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-registry
  template:
    metadata:
      labels:
        app: service-registry
    spec:
      containers:
        - name: service-registry
          image: ghcr.io/uchihaithachi/service-registry:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8761
          env:
            - name: SPRING_APPLICATION_NAME
              value: "service-registry"
            - name: SERVER_PORT
              value: "8761"
            - name: REGISTER_WITH_EUREKA
              value: "false"
            - name: FETCH_REGISTRY
              value: "false"
            - name: SPRING_PROFILES_ACTIVE
              value: "kubernetes"
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8761
            initialDelaySeconds: 60 # Adjusted for typical Spring Boot app startup
            periodSeconds: 15
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8761
            initialDelaySeconds: 30 # Adjusted
            periodSeconds: 10
          resources:
            requests:
              cpu: "75m"  # Was 100m
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
