global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "employee-service"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["employee-service:8084"]

  - job_name: "department-service"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["department-service:8083"]

  - job_name: "config-server"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["config-server:8888"]

  - job_name: "service-registry"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["service-registry:8761"]

  - job_name: "api-gateway"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["api-gateway:9191"]

  - job_name: "nginx"
    static_configs:
      - targets: ["nginx-exporter:9113"]
