apiVersion: v1
kind: Service
metadata:
  name: elasticsearch # Matches StatefulSet serviceName
  namespace: ems-app
  labels:
    app: elasticsearch
spec:
  selector:
    app: elasticsearch
  clusterIP: None
  ports:
    - name: http
      port: 9200
      targetPort: 9200
    - name: transport
      port: 9300
      targetPort: 9300
