apiVersion: v1
kind: Service
metadata:
  name: mysql-employee # Matches StatefulSet serviceName
  namespace: ems-app
  labels:
    app: mysql-employee
spec:
  selector:
    app: mysql-employee
  clusterIP: None
  ports:
    - name: mysql
      port: 3306
      targetPort: 3306
