apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql-employee
  namespace: ems-app
  labels:
    app: mysql-employee
spec:
  serviceName: mysql-employee # Headless service for StatefulSet
  replicas: 1
  selector:
    matchLabels:
      app: mysql-employee
  template:
    metadata:
      labels:
        app: mysql-employee
    spec:
      initContainers:
        - name: copy-init-scripts
          image: busybox
          command: ['sh', '-c', 'cp /configmap-scripts/employee-init.sql /target-initdbd/ && echo "Copied employee-init.sql"']
          volumeMounts:
            - name: init-scripts-cm
              mountPath: /configmap-scripts
            - name: initdb-scripts-vol
              mountPath: /target-initdbd
      containers:
        - name: mysql-employee
          image: mysql:8
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: employee-db-secret
                  key: MYSQL_ROOT_PASSWORD
            - name: MYSQL_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: mysql-employee-config
                  key: DB_NAME
          livenessProbe:
            exec:
              command:
                - "mysqladmin"
                - "ping"
                - "-h"
                - "127.0.0.1"
                - "-u"
                - "root"
                - "-p${MYSQL_ROOT_PASSWORD}"
            initialDelaySeconds: 45
            periodSeconds: 15
          readinessProbe:
            exec:
              command:
                - "mysqladmin"
                - "ping"
                - "-h"
                - "127.0.0.1"
                - "-u"
                - "root"
                - "-p${MYSQL_ROOT_PASSWORD}"
            initialDelaySeconds: 20
            periodSeconds: 10
          volumeMounts:
            - name: data
              mountPath: /var/lib/mysql
            - name: initdb-scripts-vol # Mount the same emptyDir volume
              mountPath: /docker-entrypoint-initdb.d
          resources:
            requests:
              cpu: "100m" # Was 200m
              memory: "512Mi"
            limits:
              cpu: "500m"
              memory: "1Gi"
      volumes:
        - name: init-scripts-cm # Volume for ConfigMap
          configMap:
            name: mysql-employee-init-scripts
        - name: initdb-scripts-vol # emptyDir volume shared by init and main container
          emptyDir: {}
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 5Gi
