apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: ems-app
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
    scrape_configs:
      - job_name: 'prometheus'
        static_configs:
          - targets: ['localhost:9090']
      - job_name: 'api-gateway'
        metrics_path: /actuator/prometheus
        static_configs:
          - targets: ['api-gateway:8080']
      - job_name: 'department-service'
        metrics_path: /actuator/prometheus
        static_configs:
          - targets: ['department-service:8081']
      - job_name: 'employee-service'
        metrics_path: /actuator/prometheus
        static_configs:
          - targets: ['employee-service:8082']
      - job_name: 'config-server'
        metrics_path: /actuator/prometheus
        static_configs:
          - targets: ['config-server:8888']
      - job_name: 'service-registry'
        metrics_path: /actuator/prometheus
        static_configs:
          - targets: ['service-registry:8761']
