name: CI Workflow

on:
  push:
    branches: [ main ] # Or your default branch
  pull_request:
    branches: [ main ] # Or your default branch

env:
  REGISTRY: ghcr.io
  IMAGE_NAME_PREFIX: ${{ github.repository_owner }}/ # Using owner as prefix, can be customized

jobs:
  build_and_push_images:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write # Needed to push to GitHub Container Registry

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push images
        run: |
          chmod +x cicd.sh
          ./cicd.sh build_and_push
        env:
          GIT_COMMIT_SHA: ${{ github.sha }} # Pass commit SHA to the script
          # You'll need to add secrets to your GitHub repository for these if your script needs them
          # GIT_PAT: ${{ secrets.GIT_PAT }}
          # MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
          # etc. for all secrets needed by docker-compose build or the script itself.
